services:
  backend:
    build:
      context: ./backend/EmployeeManagement.Api
    ports:
      - "5000:8080"
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=employees;Username=postgres;Password=admin
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend/employee-management
    ports:
      - "4935:80"
    depends_on:
      - backend
    networks:
      - app-network

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: employees
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

# <-- Esses dois blocos devem estar no mesmo nível que "services", NÃO dentro dele!
volumes:
  pgdata:

networks:
  app-network:
    driver: bridge
